### ISSUE TITLE
Adicionar repositórios do projeto e de análise como subrepositórios

### ISSUE THREAD

**Issue by lubianat** [jvfe/paper_wdt_panglao#1]
Não sei qual é a melhor forma de linkar os 3 na verdade. 

Outra opção são links no readme. O que acha?

**Comment by jvfe** [comment]
Opa, a ideia é manter tudo centralizado no compendium.

Se você der uma olhada no diretório manuscripts https://github.com/jvfe/wikidata_panglaodb/tree/master/manuscripts eu coloquei o manuscrito original da ideia como um submódulo, minha ideia era colocar esse como um submódulo no mesmo diretório também.

Manter tudo centralizado no compendium acho que é mais lógico 

Edit: Se isso te responde, pode fechar o issue.

**Comment by lubianat** [comment]
Boa, parece bom assim.
